export interface TeamData {
  name: string;
  department: string;
  year: string;
  phone: string;
  email: string;
  linkedin: string;
  favorite_dessert: string;
  role: string;
};


export const teamData: TeamData[] = [
  {
    name: "Rohit Pati",
    department: "Management",
    year: "4th",
    phone: "9643369553",
    email: "rohit.075bme031@tcioe.edu.np",
    linkedin: "linkedin.com/in/_r_pati",
    favorite_dessert: "",
    role: "Team Manager",
  },
  {
    name: "Abhishek Kandel",
    department: "Management",
    year: "4th",
    phone: "9861308917",
    email: "",
    linkedin: "",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Sharad Timilsina",
    department: "Bodywork",
    year: "4th",
    phone: "9869664640",
    email: "sharadtimilsina3@gmail.com",
    linkedin: "linkedin.com/in/_173255",
    favorite_dessert: "",
    role: "Body and Aerodynamics",
  },
  {
    name: "Bibek Sharma",
    department: "Communication",
    year: "3rd",
    phone: "9868990797",
    email: "sharmabibek880@gmail.com",
    linkedin: "linkedin.com/in/_95939",
    favorite_dessert: "Icecream",
    role: "Partnership Manager",
  },
  {
    name: "Bishal Gautam",
    department: "Chassis",
    year: "3rd",
    phone: "9846179313",
    email: "gtm.bishal57@gmail.com",
    linkedin: "linkedin.com/in/_332266",
    favorite_dessert: "",
    role: "Chassis Engineer",
  },
  {
    name: "Subash Bhujel",
    department: "Vehicle Dynamics",
    year: "3rd",
    phone: "9843810177",
    email: "ronaldliomes@gmail.com",
    linkedin: "",
    favorite_dessert: "WD-40",
    role: "Bodywork support Engineer",
  },
  {
    name: "Birat Poudel",
    department: "Communication",
    year: "3rd",
    phone: "9861281912",
    email: "poudel.birat25@gmail.com",
    linkedin: "linkedin.com/in/_ba18bf",
    favorite_dessert: "Vanilla Ice-cream",
    role: "Communication Manager",
  },
  {
    name: "Aashish Pant",
    department: "Communication",
    year: "3rd",
    phone: "9865376629",
    email: "aashishpnt@gmail.com",
    linkedin: "linkedin.com/in/_95180",
    favorite_dessert: "",
    role: "Event manager",
  },
  {
    name: "Sharan Shakya",
    department: "Motor & Powertrain",
    year: "3rd",
    phone: "9861000634",
    email: "sharanshakya011101101@gmail.com",
    linkedin: "linkedin.com/in/_879297",
    favorite_dessert: "cup cake",
    role: "Powertrain engineer",
  },
  {
    name: "Joseph Thapa Magar",
    department: "Electronics",
    year: "3rd",
    phone: "9865212344",
    email: "josephthapa911@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "Electronics Engineer",
  },
  {
    name: "Bivek Raymajhi",
    department: "Vehicle Dynamics",
    year: "3rd",
    phone: "9823070612",
    email: "raymajhibivek2059@gmail.com",
    linkedin: "linkedin.com/in/_b4193f",
    favorite_dessert: "",
    role: "Chassis Engineer",
  },
  {
    name: "Elish Khadka",
    department: "Vehicle Dynamics",
    year: "2nd",
    phone: "9863453114",
    email: "alishkdk2000@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "Chassis Engineer",
  },
  {
    name: "Arun Koirala",
    department: "Motor & Powertrain",
    year: "4th",
    phone: "9813786373",
    email: "arunkoiralak47@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "Powertrain engineer",
  },
  {
    name: "Divyan Acharya",
    department: "Chassis",
    year: "2nd",
    phone: "9867232280",
    email: "divyanacharya777@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Bikala Poudel",
    department: "Vehicle Dynamics",
    year: "2nd",
    phone: "9745413599",
    email: "poudelbikalpa21@gmail.com",
    linkedin: "linkedin.com/in/_cdd6fd",
    favorite_dessert: "",
    role: "Suspension Engineer",
  },
  {
    name: "Milan Shrestha",
    department: "Bodywork",
    year: "2nd",
    phone: "9843787292",
    email: "ms6297866@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Nischal Karki",
    department: "Vehicle Dynamics",
    year: "2nd",
    phone: "9840113042",
    email: "karkinischal993@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "brakes and wheel engineer",
  },
  {
    name: "Ragiv Dhakal",
    department: "Chassis",
    year: "2nd",
    phone: "9863444580",
    email: "ragivdhakal@gmail.com",
    linkedin: "linkedin.com/in/_51243f",
    favorite_dessert: "",
    role: "Chassis Designer",
  },
  {
    name: "Ayush Raj Shah",
    department: "Electronics",
    year: "3rd",
    phone: "9823161343",
    email: "ayush.078bme006@tcioe.edu.np",
    linkedin: "",
    favorite_dessert: "Say no to sugar",
    role: "",
  },
  {
    name: "Laxman bhandari",
    department: "Communication",
    year: "1st",
    phone: "9844711234",
    email: "laxamanbhanadari23@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Prashna Poudel",
    department: "Communication",
    year: "1st",
    phone: "9803305058",
    email: "prashnapoudel15@gmail.com",
    linkedin: "linkedin.com/in/_112442",
    favorite_dessert: "",
    role: "content writer",
  },
  {
    name: "Roshan Thapa",
    department: "Communication",
    year: "2nd",
    phone: "9840034583",
    email: "thaparoshan3722@gmail.com",
    linkedin: "linkedin.com/in/_658053",
    favorite_dessert: "anything that is sweet",
    role: "Blender - 3D Modelling and Animation",
  },
  {
    name: "Pukar Khanal",
    department: "Bodywork",
    year: "2nd",
    phone: "9860988898",
    email: "pukarkhanal003@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "CFD Engineer",
  },
  {
    name: "Rituram Ojha",
    department: "Electronics",
    year: "3rd",
    phone: "9866416491",
    email: "bikashojha904@gmail.com",
    linkedin: "linkedin.com/in/_moghak",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Kristina Bhandari",
    department: "Autonomous",
    year: "2nd",
    phone: "9866416491",
    email: "christinabhandari60@gmail.com",
    linkedin: "linkedin.com/in/_47209",
    favorite_dessert: "",
    role: "Autonomous Support",
  },
  {
    name: "Rajendra Baskota",
    department: "Autonomous",
    year: "3rd",
    phone: "9843590911",
    email: "raj.baskota056@gmail.com",
    linkedin: "linkedin.com/in/_rdb034",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Prabin Bohara",
    department: "Autonomous",
    year: "3rd",
    phone: "9840384109",
    email: "prabinbohara10@gmail.com",
    linkedin: "linkedin.com/in/_hara10",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Girish Bhattarai",
    department: "Communication",
    year: "3rd",
    phone: "9864593720",
    email: "girishwasistha@gmail.com",
    linkedin: "linkedin.com/in/_tarar/",
    favorite_dessert: "",
    role: "Event associate & content writer",
  },
  {
    name: "Prateek Attri",
    department: "Communication",
    year: "2nd",
    phone: "9825911047",
    email: "mishraattri2001@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "Partnership Manager",
  },
  {
    name: "Ayush Bhusal",
    department: "Communication",
    year: "3rd",
    phone: "9869926927",
    email: "ayus7h@gmail.com",
    linkedin: "linkedin.com/in._bhusal",
    favorite_dessert: "",
    role: "Partnership Manager",
  },
  {
    name: "Pabin Khanal",
    department: "Communication",
    year: "2nd",
    phone: "9864882093",
    email: "kpabin022@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "Event Associate",
  },
  {
    name: "Jatin Raut",
    department: "Communication",
    year: "2nd",
    phone: "9843041090",
    email: "jatinraut3@gmail.com",
    linkedin: "linkedin.com/in/_458317",
    favorite_dessert: "Blueberry ice-cream",
    role: "Graphics Designer",
  },
  {
    name: "Prajwol Bohara",
    department: "FEA",
    year: "2nd",
    phone: "9848390935",
    email: "prajwolbohara12@gmail.com",
    linkedin: "linkedin.com/in/_6b471f",
    favorite_dessert: "frappe",
    role: "",
  },
  {
    name: "Navaraj Dahal",
    department: "Motor & Powertrain",
    year: "3rd",
    phone: "9862241955",
    email: "navarajdahal10@gmail.com",
    linkedin: "linkedin.com/in/_b04173",
    favorite_dessert: "",
    role: "Powertrain engineer",
  },
  {
    name: "Pujan Rimal",
    department: "Vehicle Dynamics",
    year: "2nd",
    phone: "9840438225",
    email: "rimal.pujan3.14@gmail.com",
    linkedin: "linkedin.com/in/_hunged",
    favorite_dessert: "RB19",
    role: "Brakes and Wheels Engineer",
  },
  {
    name: "Aradhya Dhungel",
    department: "Electronics",
    year: "2nd",
    phone: "9803463686",
    email: "aradhyadhungelr@gmail.com",
    linkedin: "",
    favorite_dessert: "Cheesecake",
    role: "Electronics Engineer",
  },
  {
    name: "Monika Subedi",
    department: "Vehicle Dynamics",
    year: "2nd",
    phone: "9849071642",
    email: "monikasubedi987@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "Body and Aerodynamics",
  },
  {
    name: "Manish Joshi",
    department: "Web development",
    year: "2nd",
    phone: "9814630044",
    email: "manishjoc14@gmail.com",
    linkedin: "linkedin.com/in/_b2304f",
    favorite_dessert: "Chocolate",
    role: "Web dev",
  },
  {
    name: "Akal Gurung",
    department: "Vehicle Dynamics",
    year: "3rd",
    phone: "9808350819",
    email: "akalgurung23@gmail.com",
    linkedin: "",
    favorite_dessert: "Choco lava cake",
    role: "Vehicle body engineer",
  },
  {
    name: "Samuyal Giri",
    department: "FEA",
    year: "3rd",
    phone: "9804351513",
    email: "girisamuyal111@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "",
  },
  {
    name: "Ashish Chand",
    department: "Vehicle Dynamics",
    year: "2nd",
    phone: "9865651946",
    email: "ashishchand900@gmail.com",
    linkedin: "",
    favorite_dessert: "kaju katli",
    role: "CFD Engineer",
  },
  {
    name: "Prabesh Ghimire",
    department: "Chassis",
    year: "3rd",
    phone: "9810595330",
    email: "prweshghimire2078@gmail.com",
    linkedin: "",
    favorite_dessert: "",
    role: "",
  },
];
